### ISSUE TITLE
Incorrect parsing when an unquoted string with multiple numbers and dots is in the document

### ISSUE THREAD

**Issue by Xisho** [udoprog/nondestructive#1]
While using the library to process semver versions, this produces 2 problems. 
1- Semver version is parsed as number instead of string and 
2- The escape of number early terminates and `name` is not provided in the root struct.

```rust
    let contents = r#"
        version: 1.6.2
        name: "app"
    "#;

    let mut doc = yaml::from_slice(contents)?;
    let root = doc.as_ref().as_mapping().context("missing document").unwrap();
    println!("root {:?}", root);
```

Output of `root` is 
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/rust-yaml`
root {"version": Value(1.6)}

Process finished with exit code 0
```

**Comment by denizoztreves** [comment]
We also have found out some other edge cases.  

- When `keys` have `e` as the starting char the parsing stops as well. 
```rust
let contents = r#"
version: '1.4.5'
parent:
  extra: 'some_value'
"

The result with the above code

root {"version": Value('1.4.5'), "parent": Value(e)}
```

- A letter after a number is also exhibits same behaviour. 
```rust
let contents = r#"
version: '1.4.5'
memory: 600m
"

The result with above code
root {"version": Value('1.4.5'), "memory": Value(600)}
```

**Comment by udoprog** [comment]
Heh, so I guess this is why nobody wants to write a YAML parser. This is what your document looks like when fed to serde_yaml (which uses libyaml).

```text
[examples\serde-yaml.rs:8] value = Mapping {
    "version": String("1.6.2"),
    "name": String("app"),
}
```

Same thing but just `1.6` instead:

```text
[examples\serde-yaml.rs:8] value = Mapping {
    "version": Number(1.6),
    "name": String("app"),
}
```

I'll look carefully at what the spec says, but it seems like we need to try to process something as a number, but if processing completes and there's still content left on the line fall back to treat it like a string. Which is doable, but very ... interesting.

**Comment by udoprog** [comment]
Thanks for the report and reproduction cases! `0.0.16` should be out with a fix for this specific problem.

The [new testing framework](https://github.com/udoprog/nondestructive/tree/main/tests/yaml) could be a good place to start [adding some documents to better test YAML coverage](https://github.com/yaml/yaml-test-suite) if anyone is interested in finding (and fixing) more broken parsing.
